### Actividad 4.2

Ivanna Maldonado Cervantes

In [1]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
#Carga del archivo sin indice
df= pd.read_csv('listingsBoston.csv')
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69
2,6695,https://www.airbnb.com/rooms/6695,20250619031426,2025-06-19,city scrape,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Comfortable, Fully Equipped private apartment...","Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/38ac4797-e7a4...,8229,...,4.94,4.53,4.72,STR-491702,f,11,11,0,0,0.72
3,8789,https://www.airbnb.com/rooms/8789,20250619031426,2025-06-19,city scrape,Curved Glass Studio/1bd facing Park,This unit is for sale. There will need to be o...,Beacon Hill is a historic neighborhood filled ...,https://a0.muscache.com/pictures/miso/Hosting-...,26988,...,4.97,4.97,4.59,NaN,f,8,8,0,0,0.22
4,10811,https://www.airbnb.com/rooms/10811,20250619031426,2025-06-19,city scrape,Bostons Best Rentals -Studio Prestigious Back Bay,Bostons Best Rentals offers a Stunning Back Ba...,A one-square mile neighborhood that is arguabl...,https://a0.muscache.com/pictures/45735/27548f7...,38997,...,4.00,5.00,4.67,NaN,f,12,12,0,0,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4555,1442936143734248350,https://www.airbnb.com/rooms/1442936143734248350,20250619031426,2025-06-19,city scrape,"2 level, 2 bed with office in Back Bay",NaN,Step outside to immerse yourself in the quinte...,https://a0.muscache.com/pictures/prohost-api/H...,250399091,...,NaN,NaN,NaN,NaN,f,7,7,0,0,NaN
4556,1442940477243281647,https://www.airbnb.com/rooms/1442940477243281647,20250619031426,2025-06-19,city scrape,"Sunny 2BR w/ Office, Near Copley & Shopping","Stay at The Harbor Suite, a chic 2BR loft in B...",* Shopping & Dining: Steps from Newbury Street...,https://a0.muscache.com/pictures/prohost-api/H...,250399091,...,NaN,NaN,NaN,Exempt: This listing is a unit used for furnis...,f,7,7,0,0,NaN
4557,1445146141923468353,https://www.airbnb.com/rooms/1445146141923468353,20250619031426,2025-06-19,city scrape,A tree house like room in Jamaica Plain,Take it easy at this unique and tranquil getaway.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,5480536,...,NaN,NaN,NaN,STR-598354,f,2,0,2,0,NaN
4558,1445761247286385772,https://www.airbnb.com/rooms/1445761247286385772,20250619031426,2025-06-19,city scrape,NQ East Boston 3 Bdrm,This unique place has a style all its own.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,699041704,...,NaN,NaN,NaN,STR-546284,t,3,3,0,0,NaN
4559,1445867715555794708,https://www.airbnb.com/rooms/1445867715555794708,20250619031426,2025-06-19,city scrape,Stylish Boston Getaway Near Arboretum & T Stat...,Discover the very best of Boston from the comf...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,181205324,...,NaN,NaN,NaN,STR-593018,t,1,1,0,0,NaN

In [ ]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4560 entries, 0 to 4559
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            4560 non-null   int64
 1   listing_url                                   4560 non-null   object
 2   scrape_id                                     4560 non-null   int64
 3   last_scraped                                  4560 non-null   object
 4   source                                        4560 non-null   object
 5   name                                          4560 non-null   object
 6   description                                   4515 non-null   object
 7   neighborhood_overview                         2324 non-null   object
 8   picture_url                                   4560 non-null   object
 9   host_id                                       4560 non-null   int64
 10  host_url                                      4560 non-null   object
 11  host_name                                     4560 non-null   object
 12  host_since                                    4560 non-null   object
 13  host_location                                 3637 non-null   object
 14  host_about                                    3049 non-null   object
 15  host_response_time                            4029 non-null   object
 16  host_response_rate                            4029 non-null   object
 17  host_acceptance_rate                          4074 non-null   object
 18  host_is_superhost                             4384 non-null   object
 19  host_thumbnail_url                            4560 non-null   object
 20  host_picture_url                              4560 non-null   object
 21  host_neighbourhood                            4441 non-null   object
 22  host_listings_count                           4560 non-null   int64
 23  host_total_listings_count                     4560 non-null   int64
 24  host_verifications                            4560 non-null   object
 25  host_has_profile_pic                          4560 non-null   object
 26  host_identity_verified                        4560 non-null   object
 27  neighbourhood                                 2324 non-null   object
 28  neighbourhood_cleansed                        4560 non-null   object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      4560 non-null   float64
 31  longitude                                     4560 non-null   float64
 32  property_type                                 4560 non-null   object
 33  room_type                                     4560 non-null   object
 34  accommodates                                  4560 non-null   int64
 35  bathrooms                                     3731 non-null   float64
 36  bathrooms_text                                4560 non-null   object
 37  bedrooms                                      4291 non-null   float64
 38  beds                                          3726 non-null   float64
 39  amenities                                     4560 non-null   object
 40  price                                         3695 non-null   object
 41  minimum_nights                                4560 non-null   int64
 42  maximum_nights                                4560 non-null   int64
 43  minimum_minimum_nights                        4560 non-null   int64
 44  maximum_minimum_nights                        4560 non-null   int64
 45  minimum_maximum_nights                        4560 non-null   int64
 46  maximum_maximum_nights                        4560 non-null   int64
 47  minimum_nights_avg_ntm                        4560 non-null   float64
 48  maximum_nights_avg_ntm                        4560 non-null   float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              4364 non-null   object
 51  availability_30                               4560 non-null   int64
 52  availability_60                               4560 non-null   int64
 53  availability_90                               4560 non-null   int64
 54  availability_365                              4560 non-null   int64
 55  calendar_last_scraped                         4560 non-null   object
 56  number_of_reviews                             4560 non-null   int64
 57  number_of_reviews_ltm                         4560 non-null   int64
 58  number_of_reviews_l30d                        4560 non-null   int64
 59  availability_eoy                              4560 non-null   int64
 60  number_of_reviews_ly                          4560 non-null   int64
 61  estimated_occupancy_l365d                     4560 non-null   int64
 62  estimated_revenue_l365d                       3695 non-null   float64
 63  first_review                                  3494 non-null   object
 64  last_review                                   3494 non-null   object
 65  review_scores_rating                          3494 non-null   float64
 66  review_scores_accuracy                        3493 non-null   float64
 67  review_scores_cleanliness                     3494 non-null   float64
 68  review_scores_checkin                         3492 non-null   float64
 69  review_scores_communication                   3494 non-null   float64
 70  review_scores_location                        3492 non-null   float64
 71  review_scores_value                           3492 non-null   float64
 72  license                                       2997 non-null   object
 73  instant_bookable                              4560 non-null   object
 74  calculated_host_listings_count                4560 non-null   int64
 75  calculated_host_listings_count_entire_homes   4560 non-null   int64
 76  calculated_host_listings_count_private_rooms  4560 non-null   int64
 77  calculated_host_listings_count_shared_rooms   4560 non-null   int64
 78  reviews_per_month                             3494 non-null   float64
dtypes: float64(18), int64(26), object(35)
memory usage: 2.7+ MB

#### a) Los registros de 5 “host name” diferentes

In [ ]:
hosts = df['host_name'].dropna().unique()[:5]
filtro_a = df[df['host_name'].isin(hosts)]
filtro_a

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69
2,6695,https://www.airbnb.com/rooms/6695,20250619031426,2025-06-19,city scrape,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Comfortable, Fully Equipped private apartment...","Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/38ac4797-e7a4...,8229,...,4.94,4.53,4.72,STR-491702,f,11,11,0,0,0.72
3,8789,https://www.airbnb.com/rooms/8789,20250619031426,2025-06-19,city scrape,Curved Glass Studio/1bd facing Park,This unit is for sale. There will need to be o...,Beacon Hill is a historic neighborhood filled ...,https://a0.muscache.com/pictures/miso/Hosting-...,26988,...,4.97,4.97,4.59,NaN,f,8,8,0,0,0.22
4,10811,https://www.airbnb.com/rooms/10811,20250619031426,2025-06-19,city scrape,Bostons Best Rentals -Studio Prestigious Back Bay,Bostons Best Rentals offers a Stunning Back Ba...,A one-square mile neighborhood that is arguabl...,https://a0.muscache.com/pictures/45735/27548f7...,38997,...,4.00,5.00,4.67,NaN,f,12,12,0,0,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4183,1354618376723329714,https://www.airbnb.com/rooms/1354618376723329714,20250619031426,2025-06-19,city scrape,230B4.2 | The Penthouse w/WD & A,"Kick back and relax in this calm, stylish space.",NaN,https://a0.muscache.com/pictures/prohost-api/H...,71783,...,NaN,NaN,NaN,Exempt: This listing is a unit used for furnis...,t,58,18,40,0,NaN
4192,1357379278307447716,https://www.airbnb.com/rooms/1357379278307447716,20250619031426,2025-06-19,city scrape,47S1.B | The Sumner Redline | w/AC & WD | Suite,You will discover a delightful fusion of charm...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,71783,...,NaN,NaN,NaN,Exempt: This listing is a unit used for furnis...,f,58,18,40,0,NaN
4194,1358084036665475601,https://www.airbnb.com/rooms/1358084036665475601,20250619031426,2025-06-19,city scrape,39S1.g | 1BR 2B w/AC & W/D 75ft to 'C' Greenl...,Discover a city retreat that promises you urba...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,71783,...,NaN,NaN,NaN,Exempt: This listing is a unit used for furnis...,f,58,18,40,0,NaN
4195,1358159333179283935,https://www.airbnb.com/rooms/1358159333179283935,20250619031426,2025-06-19,city scrape,39S1.b | 1BR 2B w/AC & W/D 75ft to 'C' Greenline,Discover a city retreat that promises you urba...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,71783,...,NaN,NaN,NaN,Exempt: This listing is a unit used for furnis...,f,58,18,40,0,NaN
4362,1410382714154823147,https://www.airbnb.com/rooms/1410382714154823147,20250619031426,2025-06-19,city scrape,Bright & Spacious Boston,"Newly renovated and full of charm, this bright...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,27217046,...,5.00,4.88,4.88,STR-594074,f,1,1,0,0,4.80

#### b) Hosts que se unieron a Airbnb después del año 2020

In [ ]:
filtro_b = df[df['host_since'] >= "2020-01-01"]
filtro_b

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
553,16971718,https://www.airbnb.com/rooms/16971718,20250619031426,2025-06-19,city scrape,A Victorian Secret AMAZING apt. in Historic Home,Your own apartment in an historic Victorian ho...,Peaceful and diverse historic old Boston neigh...,https://a0.muscache.com/pictures/2a6b1cc6-6749...,446136994,...,4.92,4.74,4.89,STR-545299,t,1,1,0,0,3.54
1276,41915144,https://www.airbnb.com/rooms/41915144,20250619031426,2025-06-19,previous scrape,Brick and beam living in the Historic North End,Recently renovated brick and beam open concept...,"Historic North End, waterfront, faneuil hall, ...",https://a0.muscache.com/pictures/db89ce80-128c...,331562764,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
1277,41949812,https://www.airbnb.com/rooms/41949812,20250619031426,2025-06-19,city scrape,Riverway the best of Boston and Brookline!,A gorgeous 2 bedroom apartment ready to move i...,This property is across the street from the be...,https://a0.muscache.com/pictures/0b99764d-f1c2...,331970881,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
1307,42937960,https://www.airbnb.com/rooms/42937960,20250619031426,2025-06-19,previous scrape,Cozy Room in the Heart of Boston (MGH/Downtown),This is a furnished business rental only offer...,NaN,https://a0.muscache.com/pictures/2dbbb266-5514...,341885174,...,NaN,NaN,NaN,NaN,t,1,0,1,0,NaN
1341,44356157,https://www.airbnb.com/rooms/44356157,20250619031426,2025-06-19,previous scrape,"Short Term Lease or Stay in heart of Boston, MA",Reach out to us and let us know how we can hel...,NaN,https://a0.muscache.com/pictures/76e83a82-4e81...,357678751,...,NaN,NaN,NaN,Exempt: This listing is a hotel or motel,f,1,0,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4546,1440135327437250033,https://www.airbnb.com/rooms/1440135327437250033,20250619031426,2025-06-19,city scrape,Room 3 Queen bed,This stylish place to stay is perfect for your...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,329370033,...,NaN,NaN,NaN,STR-445570,f,5,1,4,0,NaN
4547,1440153513591203101,https://www.airbnb.com/rooms/1440153513591203101,20250619031426,2025-06-19,city scrape,Room 4 - Queen bed,This stylish place to stay is perfect for your...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,329370033,...,NaN,NaN,NaN,STR-445570,f,5,1,4,0,NaN
4553,1440804415467027007,https://www.airbnb.com/rooms/1440804415467027007,20250619031426,2025-06-19,city scrape,NomadiQ boutique stay,Keep it simple at this peaceful and centrally-...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,699041704,...,5.00,5.00,5.00,STR-546064,t,3,3,0,0,1.00
4554,1441542310615348047,https://www.airbnb.com/rooms/1441542310615348047,20250619031426,2025-06-19,city scrape,Quiet 2BR + Office | Midterm,Spacious and relaxing 2BR + office in a quiet ...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,700783118,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
4558,1445761247286385772,https://www.airbnb.com/rooms/1445761247286385772,20250619031426,2025-06-19,city scrape,NQ East Boston 3 Bdrm,This unique place has a style all its own.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,699041704,...,NaN,NaN,NaN,STR-546284,t,3,3,0,0,NaN

#### c) Hosts que responden “within a day”

In [ ]:
filtro_c = df[df['host_response_time'] == "within a day"]
filtro_c

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
3,8789,https://www.airbnb.com/rooms/8789,20250619031426,2025-06-19,city scrape,Curved Glass Studio/1bd facing Park,This unit is for sale. There will need to be o...,Beacon Hill is a historic neighborhood filled ...,https://a0.muscache.com/pictures/miso/Hosting-...,26988,...,4.97,4.97,4.59,NaN,f,8,8,0,0,0.22
9,40601,https://www.airbnb.com/rooms/40601,20250619031426,2025-06-19,city scrape,Private room & bath - Jamaica Plain,Private bedroom and bathroom in my house in Ja...,Jamaica Plain is a diverse neighborhood of Bos...,https://a0.muscache.com/pictures/508984/678a92...,174986,...,4.94,4.93,4.93,STR-551851,f,1,0,1,0,0.57
13,60356,https://www.airbnb.com/rooms/60356,20250619031426,2025-06-19,city scrape,Bookcase 1bd facing Boston Common,Live beside the Boston Common and the State Ho...,NaN,https://a0.muscache.com/pictures/e0b12f2f-06c3...,26988,...,4.89,5.00,4.68,NaN,f,8,8,0,0,0.13
14,67774,https://www.airbnb.com/rooms/67774,20250619031426,2025-06-19,city scrape,Corner 1 bed facing Golden Dome,Live beside the State House and the Boston Com...,This building is located in the historic area ...,https://a0.muscache.com/pictures/95ad5d58-7fc3...,26988,...,4.94,4.98,4.81,NaN,f,8,8,0,0,0.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4361,1409522571756431583,https://www.airbnb.com/rooms/1409522571756431583,20250619031426,2025-06-19,city scrape,Spectacular Boston City View,Beautiful decorated modern apartment with a gr...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,692164752,...,NaN,NaN,NaN,NaN,f,2,1,1,0,NaN
4363,1410396657230251057,https://www.airbnb.com/rooms/1410396657230251057,20250619031426,2025-06-19,city scrape,Amazing Downtown Boston CityView,Beautifully decorated and newly renovated prop...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,692164752,...,NaN,NaN,NaN,NaN,f,2,1,1,0,NaN
4426,1419511623549632301,https://www.airbnb.com/rooms/1419511623549632301,20250619031426,2025-06-19,city scrape,Classic Apartment #474,If you are looking for one of the best places ...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,558528704,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
4432,1419627988003822719,https://www.airbnb.com/rooms/1419627988003822719,20250619031426,2025-06-19,city scrape,Spacious Residence near Seasport,Experience upscale living in this stylish 2-be...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,158837906,...,NaN,NaN,NaN,str-792204,f,1,1,0,0,NaN
4499,1430687656831322110,https://www.airbnb.com/rooms/1430687656831322110,20250619031426,2025-06-19,city scrape,"Room- Andrew S, Hospitals, Beach",This fully furnished room offers a comfortable...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,518462500,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN

#### d) Filas múltiplos de 200 (200, 400, 600, …)

In [ ]:
filtro_d = df.iloc[200::200]
filtro_d

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
200,5974886,https://www.airbnb.com/rooms/5974886,20250619031426,2025-06-19,city scrape,Close to it all-private parking & red MBTA sta...,Charming 850 sq ft Apartment – Just 2 Red Line...,I have lived in this neighborhood for over a d...,https://a0.muscache.com/pictures/e3b0f5ee-3320...,23856705,...,5.00,4.79,4.91,STR-455594,f,1,1,0,0,0.27
400,12372052,https://www.airbnb.com/rooms/12372052,20250619031426,2025-06-19,city scrape,Apartment with 2-3 bedrooms-3 min to subway T ...,This is in a 3 bedroom apartment next to Sulli...,"The house is in Charlestown (part of Boston), ...",https://a0.muscache.com/pictures/42a44501-4662...,21745230,...,4.95,4.45,4.75,NaN,f,12,3,9,0,0.58
600,18290558,https://www.airbnb.com/rooms/18290558,20250619031426,2025-06-19,city scrape,★ Spacious & Modern ★ Professionally Sanitized ★,"Need a safe, clean, and comfortable place to s...",It's hard to find a better neighborhood in Bos...,https://a0.muscache.com/pictures/e18fecfa-2510...,69587,...,4.91,4.65,4.74,STR-400320,f,8,0,8,0,9.56
800,23651852,https://www.airbnb.com/rooms/23651852,20250619031426,2025-06-19,city scrape,Awesome condo in Fenway,Great 1 bedroom condo located in the heart of ...,This Airbnb is in the Fenway-Kenmore area of B...,https://a0.muscache.com/pictures/e0f54994-1c3f...,9669662,...,5.00,5.00,5.00,NaN,f,1,1,0,0,0.02
1000,29982429,https://www.airbnb.com/rooms/29982429,20250619031426,2025-06-19,city scrape,Copley House Queen Studio,Live like a local! More spacious than our Budg...,Back Bay is one of Boston's finest neighborhoo...,https://a0.muscache.com/pictures/prohost-api/H...,85130,...,4.57,4.87,4.29,Exempt: This listing is a hotel or motel,t,7,7,0,0,0.99
1200,38697559,https://www.airbnb.com/rooms/38697559,20250619031426,2025-06-19,city scrape,Large Private Bedroom in Unique and Spacious C...,Our place is a large 3rd floor condo with gorg...,Our neighborhood is really great because it is...,https://a0.muscache.com/pictures/823d496b-ddf7...,28299940,...,5.00,5.00,5.00,STR-489454,f,1,0,1,0,0.90
1400,45844741,https://www.airbnb.com/rooms/45844741,20250619031426,2025-06-19,previous scrape,Great public transportation to tour all of Bos...,"The Apartment is a three bedrooms place, livin...",We are in a Meeting House Hill one of the olde...,https://a0.muscache.com/pictures/hosting/Hosti...,366954587,...,4.96,4.58,4.79,STR-523616,t,1,1,0,0,1.58
1600,50009772,https://www.airbnb.com/rooms/50009772,20250619031426,2025-06-19,city scrape,Spacious & newly renovated private room!,Stay in my traditional Dorchester (Boston) sty...,Dorchester is the largest neighborhood in Bost...,https://a0.muscache.com/pictures/miso/Hosting-...,15583990,...,4.83,4.63,4.58,STR-453623,f,7,2,5,0,0.52
1800,53477851,https://www.airbnb.com/rooms/53477851,20250619031426,2025-06-19,city scrape,109S14 | The Strathmore 14 w/AC | 2BR 1B | Pri...,Discover a cozy city retreat that promises urb...,Brighton is a dissolved municipality and curre...,https://a0.muscache.com/pictures/prohost-api/H...,71783,...,3.71,4.86,3.57,NaN,f,58,18,40,0,0.18
2000,625824021434996394,https://www.airbnb.com/rooms/625824021434996394,20250619031426,2025-06-19,city scrape,"Blueground | Back Bay, laundry & gym",Show up and start living from day one in Bosto...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,107434423,...,NaN,NaN,NaN,NaN,t,369,369,0,0,NaN
2200,715658190467254169,https://www.airbnb.com/rooms/715658190467254169,20250619031426,2025-06-19,city scrape,"Blueground | South Boston, nr restaurants",Show up and start living from day one in Bosto...,This furnished home is located in South Boston...,https://a0.muscache.com/pictures/prohost-api/H...,107434423,...,4.00,5.00,4.00,NaN,t,369,369,0,0,0.08
2400,828386525464240771,https://www.airbnb.com/rooms/828386525464240771,20250619031426,2025-06-19,city scrape,Beautiful Newbury St. 1Br,This wonderful 1 bedroom apartment is located ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,275849638,...,4.86,4.92,4.52,STR-520909,f,70,70,0,0,4.08
2600,920192802910045769,https://www.airbnb.com/rooms/920192802910045769,20250619031426,2025-06-19,previous scrape,"Art boutique studio ""Moody Cat"" in Charlestown.",The cozy studio is in excellent condition: eat...,Nice and safe area - Charlestown. Near T-stati...,https://a0.muscache.com/pictures/hosting/Hosti...,492835190,...,4.86,4.86,4.14,NaN,t,3,3,0,0,0.32
2800,971056828621546341,https://www.airbnb.com/rooms/971056828621546341,20250619031426,2025-06-19,previous scrape,Sparkling 2BR / 2Ba in Back Bay,Welcome to our modern apartment located in the...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,163848078,...,NaN,NaN,NaN,STR-366118,f,95,95,0,0,NaN
3000,1025453548901747932,https://www.airbnb.com/rooms/1025453548901747932,20250619031426,2025-06-19,city scrape,South End Serene Studio,Escape to urban serenity at the South End Sere...,This apartment is located on the southeastern ...,https://a0.muscache.com/pictures/miso/Hosting-...,382451810,...,4.92,4.92,4.42,Exempt: This listing is a unit that has contra...,t,54,54,0,0,0.67
3200,1086284791906225107,https://www.airbnb.com/rooms/1086284791906225107,20250619031426,2025-06-19,city scrape,Lux 2br in the Heart of FIDI!,This enormous 2 bedroom apartment is located i...,The Financial District is downtown’s business ...,https://a0.muscache.com/pictures/miso/Hosting-...,382451810,...,4.96,4.94,4.60,Exempt: This listing is a unit that has contra...,t,54,54,0,0,4.69
3400,1145750495561922282,https://www.airbnb.com/rooms/1145750495561922282,20250619031426,2025-06-19,city scrape,"Premier King Skyline, Revere Hotel, Near Fenway",Explore Boston's soul from our doorstep! We're...,- Boston Common - 0.2 miles<br />- Boston Publ...,https://a0.muscache.com/pictures/prohost-api/H...,501999278,...,NaN,NaN,NaN,Exempt: This listing is a hotel or motel,t,46,0,0,0,NaN
3600,1212902723759772095,https://www.airbnb.com/rooms/1212902723759772095,20250619031426,2025-06-19,city scrape,Stylish 3BR Near Logan & Subway – Prime Location,Enjoy comfort and convenience in this modern 3...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,245199133,...,4.95,4.75,4.83,STR-492396,f,4,4,0,0,3.74
3800,1289108921740189349,https://www.airbnb.com/rooms/1289108921740189349,20250619031426,2025-06-19,city scrape,Blueground | Dorchester studio apartment,"Discover the best of Boston, with this studio ...",Set yourself up in this furnished apartment in...,https://a0.muscache.com/pictures/prohost-api/H...,107434423,...,NaN,NaN,NaN,NaN,t,369,369,0,0,NaN
4000,1341432002799739410,https://www.airbnb.com/rooms/1341432002799739410,20250619031426,2025-06-19,city scrape,Huge Studio in Downtown Boston 9904,Please click on -show more- and read the descr...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,212359760,...,5.00,5.00,4.83,STR-511551,t,64,64,0,0,3.10
4200,1358348550389604685,https://www.airbnb.com/rooms/1358348550389604685,20250619031426,2025-06-19,city scrape,Spacious Back Bay 1BR w/ King & Office,Discover the charm of Destiny Lofts’ Copley Su...,Step outside to immerse yourself in the quinte...,https://a0.muscache.com/pictures/miso/Hosting-...,96961013,...,5.00,5.00,5.00,Exempt: This listing is a hotel or motel,f,21,21,0,0,2.00
4400,1414511119752689162,https://www.airbnb.com/rooms/1414511119752689162,20250619031426,2025-06-19,city scrape,Modern Penthouse (2BR 2BA) Stunning Lake Views,You'll have a great time at this comfortable p...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,163848078,...,5.00,5.00,4.00,STR-111235,t,95,95,0,0,1.00

#### e) Tipos de cuarto: “Entire home” y “Private room”

In [ ]:
filtro_e = df[df['room_type'].isin(["Entire home/apt", "Private room"])]
filtro_e

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69
2,6695,https://www.airbnb.com/rooms/6695,20250619031426,2025-06-19,city scrape,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Comfortable, Fully Equipped private apartment...","Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/38ac4797-e7a4...,8229,...,4.94,4.53,4.72,STR-491702,f,11,11,0,0,0.72
3,8789,https://www.airbnb.com/rooms/8789,20250619031426,2025-06-19,city scrape,Curved Glass Studio/1bd facing Park,This unit is for sale. There will need to be o...,Beacon Hill is a historic neighborhood filled ...,https://a0.muscache.com/pictures/miso/Hosting-...,26988,...,4.97,4.97,4.59,NaN,f,8,8,0,0,0.22
4,10811,https://www.airbnb.com/rooms/10811,20250619031426,2025-06-19,city scrape,Bostons Best Rentals -Studio Prestigious Back Bay,Bostons Best Rentals offers a Stunning Back Ba...,A one-square mile neighborhood that is arguabl...,https://a0.muscache.com/pictures/45735/27548f7...,38997,...,4.00,5.00,4.67,NaN,f,12,12,0,0,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4555,1442936143734248350,https://www.airbnb.com/rooms/1442936143734248350,20250619031426,2025-06-19,city scrape,"2 level, 2 bed with office in Back Bay",NaN,Step outside to immerse yourself in the quinte...,https://a0.muscache.com/pictures/prohost-api/H...,250399091,...,NaN,NaN,NaN,NaN,f,7,7,0,0,NaN
4556,1442940477243281647,https://www.airbnb.com/rooms/1442940477243281647,20250619031426,2025-06-19,city scrape,"Sunny 2BR w/ Office, Near Copley & Shopping","Stay at The Harbor Suite, a chic 2BR loft in B...",* Shopping & Dining: Steps from Newbury Street...,https://a0.muscache.com/pictures/prohost-api/H...,250399091,...,NaN,NaN,NaN,Exempt: This listing is a unit used for furnis...,f,7,7,0,0,NaN
4557,1445146141923468353,https://www.airbnb.com/rooms/1445146141923468353,20250619031426,2025-06-19,city scrape,A tree house like room in Jamaica Plain,Take it easy at this unique and tranquil getaway.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,5480536,...,NaN,NaN,NaN,STR-598354,f,2,0,2,0,NaN
4558,1445761247286385772,https://www.airbnb.com/rooms/1445761247286385772,20250619031426,2025-06-19,city scrape,NQ East Boston 3 Bdrm,This unique place has a style all its own.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,699041704,...,NaN,NaN,NaN,STR-546284,t,3,3,0,0,NaN
4559,1445867715555794708,https://www.airbnb.com/rooms/1445867715555794708,20250619031426,2025-06-19,city scrape,Stylish Boston Getaway Near Arboretum & T Stat...,Discover the very best of Boston from the comf...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,181205324,...,NaN,NaN,NaN,STR-593018,t,1,1,0,0,NaN

#### f) Registros con a lo mucho 4 camas

In [ ]:
filtro_f = df[df['beds'] <= 4]
filtro_f

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69
2,6695,https://www.airbnb.com/rooms/6695,20250619031426,2025-06-19,city scrape,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Comfortable, Fully Equipped private apartment...","Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/38ac4797-e7a4...,8229,...,4.94,4.53,4.72,STR-491702,f,11,11,0,0,0.72
3,8789,https://www.airbnb.com/rooms/8789,20250619031426,2025-06-19,city scrape,Curved Glass Studio/1bd facing Park,This unit is for sale. There will need to be o...,Beacon Hill is a historic neighborhood filled ...,https://a0.muscache.com/pictures/miso/Hosting-...,26988,...,4.97,4.97,4.59,NaN,f,8,8,0,0,0.22
4,10811,https://www.airbnb.com/rooms/10811,20250619031426,2025-06-19,city scrape,Bostons Best Rentals -Studio Prestigious Back Bay,Bostons Best Rentals offers a Stunning Back Ba...,A one-square mile neighborhood that is arguabl...,https://a0.muscache.com/pictures/45735/27548f7...,38997,...,4.00,5.00,4.67,NaN,f,12,12,0,0,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4555,1442936143734248350,https://www.airbnb.com/rooms/1442936143734248350,20250619031426,2025-06-19,city scrape,"2 level, 2 bed with office in Back Bay",NaN,Step outside to immerse yourself in the quinte...,https://a0.muscache.com/pictures/prohost-api/H...,250399091,...,NaN,NaN,NaN,NaN,f,7,7,0,0,NaN
4556,1442940477243281647,https://www.airbnb.com/rooms/1442940477243281647,20250619031426,2025-06-19,city scrape,"Sunny 2BR w/ Office, Near Copley & Shopping","Stay at The Harbor Suite, a chic 2BR loft in B...",* Shopping & Dining: Steps from Newbury Street...,https://a0.muscache.com/pictures/prohost-api/H...,250399091,...,NaN,NaN,NaN,Exempt: This listing is a unit used for furnis...,f,7,7,0,0,NaN
4557,1445146141923468353,https://www.airbnb.com/rooms/1445146141923468353,20250619031426,2025-06-19,city scrape,A tree house like room in Jamaica Plain,Take it easy at this unique and tranquil getaway.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,5480536,...,NaN,NaN,NaN,STR-598354,f,2,0,2,0,NaN
4558,1445761247286385772,https://www.airbnb.com/rooms/1445761247286385772,20250619031426,2025-06-19,city scrape,NQ East Boston 3 Bdrm,This unique place has a style all its own.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,699041704,...,NaN,NaN,NaN,STR-546284,t,3,3,0,0,NaN
4559,1445867715555794708,https://www.airbnb.com/rooms/1445867715555794708,20250619031426,2025-06-19,city scrape,Stylish Boston Getaway Near Arboretum & T Stat...,Discover the very best of Boston from the comf...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,181205324,...,NaN,NaN,NaN,STR-593018,t,1,1,0,0,NaN

#### g) Registros que sean superhost

In [ ]:
filtro_g = df[df['host_is_superhost'] == "t"]
filtro_g

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69
2,6695,https://www.airbnb.com/rooms/6695,20250619031426,2025-06-19,city scrape,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Comfortable, Fully Equipped private apartment...","Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/38ac4797-e7a4...,8229,...,4.94,4.53,4.72,STR-491702,f,11,11,0,0,0.72
3,8789,https://www.airbnb.com/rooms/8789,20250619031426,2025-06-19,city scrape,Curved Glass Studio/1bd facing Park,This unit is for sale. There will need to be o...,Beacon Hill is a historic neighborhood filled ...,https://a0.muscache.com/pictures/miso/Hosting-...,26988,...,4.97,4.97,4.59,NaN,f,8,8,0,0,0.22
4,10811,https://www.airbnb.com/rooms/10811,20250619031426,2025-06-19,city scrape,Bostons Best Rentals -Studio Prestigious Back Bay,Bostons Best Rentals offers a Stunning Back Ba...,A one-square mile neighborhood that is arguabl...,https://a0.muscache.com/pictures/45735/27548f7...,38997,...,4.00,5.00,4.67,NaN,f,12,12,0,0,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4536,1437666832351015742,https://www.airbnb.com/rooms/1437666832351015742,20250619031426,2025-06-19,city scrape,558/2 - 3BR Boston | Renovated Nest near Aquarium,"To our valued guests, please be aware that the...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,671166370,...,NaN,NaN,NaN,STR-573021,f,4,4,0,0,NaN
4543,1439369159567368388,https://www.airbnb.com/rooms/1439369159567368388,20250619031426,2025-06-19,city scrape,Room 2 - two queen beds,This stylish place to stay is perfect for your...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,329370033,...,NaN,NaN,NaN,STR-445570,f,5,1,4,0,NaN
4545,1440125124822411925,https://www.airbnb.com/rooms/1440125124822411925,20250619031426,2025-06-19,city scrape,Room 1 King Bed,This stylish place to stay is perfect for your...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,329370033,...,NaN,NaN,NaN,STR-445570,f,5,1,4,0,NaN
4546,1440135327437250033,https://www.airbnb.com/rooms/1440135327437250033,20250619031426,2025-06-19,city scrape,Room 3 Queen bed,This stylish place to stay is perfect for your...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,329370033,...,NaN,NaN,NaN,STR-445570,f,5,1,4,0,NaN
4547,1440153513591203101,https://www.airbnb.com/rooms/1440153513591203101,20250619031426,2025-06-19,city scrape,Room 4 - Queen bed,This stylish place to stay is perfect for your...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,329370033,...,NaN,NaN,NaN,STR-445570,f,5,1,4,0,NaN

#### h) Columnas impares

In [ ]:
filtro_h = df.iloc[:, 1::2]
filtro_h

,listing_url,last_scraped,name,neighborhood_overview,host_id,host_name,host_location,host_response_time,host_acceptance_rate,host_thumbnail_url,...,availability_eoy,estimated_occupancy_l365d,first_review,review_scores_rating,review_scores_cleanliness,review_scores_communication,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_shared_rooms
0,https://www.airbnb.com/rooms/3781,2025-06-19,HARBORSIDE-Walk to subway,"Mostly quiet ( no loud music, no crowed sidewa...",4804,Frank,"Massachusetts, United States",within a day,13%,https://a0.muscache.com/im/users/4804/profile_...,...,93,58,2015-07-10,4.96,4.96,4.96,4.88,f,1,0
1,https://www.airbnb.com/rooms/5506,2025-06-19,** Fort Hill Inn Private! Minutes to center!**,"Peaceful, Architecturally interesting, histori...",8229,Terry,"Boston, MA",within an hour,100%,https://a0.muscache.com/im/users/8229/profile_...,...,103,78,2009-03-21,4.82,4.91,4.89,4.77,f,11,0
2,https://www.airbnb.com/rooms/6695,2025-06-19,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Peaceful, Architecturally interesting, histori...",8229,Terry,"Boston, MA",within an hour,100%,https://a0.muscache.com/im/users/8229/profile_...,...,93,66,2009-08-06,4.81,4.85,4.94,4.72,f,11,0
3,https://www.airbnb.com/rooms/8789,2025-06-19,Curved Glass Studio/1bd facing Park,Beacon Hill is a historic neighborhood filled ...,26988,Anne,"Boston, MA",within a day,38%,https://a0.muscache.com/im/pictures/user/d7d71...,...,41,0,2014-08-12,4.69,4.55,4.97,4.59,f,8,0
4,https://www.airbnb.com/rooms/10811,2025-06-19,Bostons Best Rentals -Studio Prestigious Back Bay,A one-square mile neighborhood that is arguabl...,38997,Michelle,NaN,within a few hours,53%,https://a0.muscache.com/im/pictures/user/13444...,...,175,0,2016-01-09,4.33,4.67,4.00,4.67,f,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4555,https://www.airbnb.com/rooms/1442936143734248350,2025-06-19,"2 level, 2 bed with office in Back Bay",Step outside to immerse yourself in the quinte...,250399091,Nina,NaN,within an hour,100%,https://a0.muscache.com/im/pictures/user/User/...,...,144,0,NaN,NaN,NaN,NaN,NaN,f,7,0
4556,https://www.airbnb.com/rooms/1442940477243281647,2025-06-19,"Sunny 2BR w/ Office, Near Copley & Shopping",* Shopping & Dining: Steps from Newbury Street...,250399091,Nina,NaN,within an hour,100%,https://a0.muscache.com/im/pictures/user/User/...,...,189,0,NaN,NaN,NaN,NaN,NaN,f,7,0
4557,https://www.airbnb.com/rooms/1445146141923468353,2025-06-19,A tree house like room in Jamaica Plain,NaN,5480536,Allison,"Boston, MA",within an hour,96%,https://a0.muscache.com/im/pictures/user/User/...,...,190,0,NaN,NaN,NaN,NaN,NaN,f,0,0
4558,https://www.airbnb.com/rooms/1445761247286385772,2025-06-19,NQ East Boston 3 Bdrm,NaN,699041704,Olsian,NaN,within an hour,100%,https://a0.muscache.com/im/pictures/user/User/...,...,189,0,NaN,NaN,NaN,NaN,NaN,t,3,0
4559,https://www.airbnb.com/rooms/1445867715555794708,2025-06-19,Stylish Boston Getaway Near Arboretum & T Stat...,NaN,181205324,Plushy,"Scottsdale, AZ",within an hour,98%,https://a0.muscache.com/im/pictures/user/e39e3...,...,195,0,NaN,NaN,NaN,NaN,NaN,t,1,0

In [ ]:
filtro_a.to_csv("filtro_a.csv")
filtro_b.to_csv("filtro_b.csv")
filtro_c.to_csv("filtro_c.csv")
filtro_d.to_csv("filtro_d.csv")
filtro_e.to_csv("filtro_e.csv")
filtro_f.to_csv("filtro_f.csv")
filtro_g.to_csv("filtro_g.csv")
filtro_h.to_csv("filtro_h.csv")