### Actividad 5.3

Ivanna Maldonado C.

In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('listingsBoston.csv')
data["price"] = data["price"].replace('[\$,]', '', regex=True)
data["price"] = data["price"].astype(float)
data.head(2)

<>:3: SyntaxWarning: invalid escape sequence '\$'
<>:3: SyntaxWarning: invalid escape sequence '\$'
/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_7336/3875637894.py:3: SyntaxWarning: invalid escape sequence '\$'
  data["price"] = data["price"].replace('[\$,]', '', regex=True)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69

In [3]:
#Corroboramos valores nulos
valores_nulos=data.isnull().mean()
valores_nulos

id                                              0.000000
listing_url                                     0.000000
scrape_id                                       0.000000
last_scraped                                    0.000000
source                                          0.000000
                                                  ...
calculated_host_listings_count                  0.000000
calculated_host_listings_count_entire_homes     0.000000
calculated_host_listings_count_private_rooms    0.000000
calculated_host_listings_count_shared_rooms     0.000000
reviews_per_month                               0.233772
Length: 79, dtype: float64

In [4]:
#Realizamos una copia del dataframe 
data1=data.copy()

In [5]:
#Eliminar columnas innecesarias
#Estas tres columnas están en su mayoría vacías, neighbourhood_overview no es tan relevante y está 49% vacía
data2= data1.drop(['neighborhood_overview', 'calendar_updated', 'neighbourhood_group_cleansed'], axis=1)
data2.head(2)

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,https://a0.muscache.com/pictures/24670/b2de044...,4804,https://www.airbnb.com/users/show/4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,https://a0.muscache.com/pictures/miso/Hosting-...,8229,https://www.airbnb.com/users/show/8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69

In [6]:
#Sustituir valores nulos por un STRING en  concreto 
#Rellenamos con NO DESCRIPTION porque no hay forma de saber la descripción de una propiedad
data2["description"] =data2["description"].fillna("No description")

In [7]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [8]:
#Sustituir valores nulos por un STRING en  concreto 
#Rellenamos con Boston, MA. porque la mayoría de los hosts son de ahí y sería el "promedio" de los datos.
data2["host_location"] =data2["host_location"].fillna("Boston, MA")

In [9]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [10]:
#Sustituir valores nulos por un STRING en  concreto 
#Rellenamos con No INFO porque no podemos saber los datos de los hosts.
data2["host_about"] =data2["host_about"].fillna("No information")

In [11]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [12]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
#Filtro por columnas
data2["host_response_time"] =data2["host_response_time"].fillna(method="ffill")

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_7336/1220790007.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["host_response_time"] =data2["host_response_time"].fillna(method="ffill")

In [13]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [14]:
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
# Como son %, es muy complicado quitar el signo y cambiar de string a int.
data2["host_response_rate"] =data2["host_response_rate"].fillna(method="bfill")

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_7336/3542546518.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["host_response_rate"] =data2["host_response_rate"].fillna(method="bfill")

In [15]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [16]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
#Filtro por columnas
data2["host_acceptance_rate"] =data2["host_acceptance_rate"].fillna(method="ffill")

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_7336/3225591725.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["host_acceptance_rate"] =data2["host_acceptance_rate"].fillna(method="ffill")

In [17]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [18]:
#Sustituir valores nulos por un STRING en  concreto 
#Se sustituye con el tipo de host más común
data2["host_is_superhost"] =data2["host_is_superhost"].fillna("f")

In [19]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [20]:
#Sustituir valores nulos por un STRING en  concreto 
#El vecindario del host no es tan importante, por lo que se rellena con NON SPECIFIED
data2["host_neighbourhood"] =data2["host_neighbourhood"].fillna("Non specified")

In [21]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [22]:
#Sustituir valores nulos por un STRING en  concreto 
#Se sustituye con el unico string que se encuentra en la base de datos
data2["neighbourhood"] =data2["neighbourhood"].fillna("Neighbourhood highlights")

In [23]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [24]:
#Sustituir valores nulos con promedio o media
data2["bathrooms"]=data2["bathrooms"].fillna("0")

In [25]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [26]:
#Sustituir valores nulos con promedio o media
data2["bedrooms"]=data2["bedrooms"].fillna(round(data1["bedrooms"].mean(),1))

In [27]:
#Sustituir valores nulos con promedio o media
data2["beds"]=data2["beds"].fillna(round(data1["beds"].mean(),1))

In [28]:
#Sustituir valores nulos con promedio o media
#Al inicio quité el signo de $ de price, así que puedo usar mean para rellenar
data2["price"]=data2["price"].fillna(round(data1["price"].mean(),1))

In [29]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [30]:
#Sustituir valores nulos por un STRING en  concreto, en su mayoría es TRUE
data2["has_availability"] =data2["has_availability"].fillna("t")

In [31]:
#Sustituir valores nulos con promedio o media
data2["estimated_revenue_l365d"]=data2["estimated_revenue_l365d"].fillna(round(data1["estimated_revenue_l365d"].mean(),1))

In [32]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [33]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
data2["first_review"] =data2["first_review"].fillna(method="ffill")

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_7336/2007489826.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["first_review"] =data2["first_review"].fillna(method="ffill")

In [34]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
data2["last_review"] =data2["last_review"].fillna(method="ffill")

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_7336/542261576.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["last_review"] =data2["last_review"].fillna(method="ffill")

In [35]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [36]:
#Sustituir valores nulos con promedio o media
#Las últimas variables son todas numéricas, así que decidí usar la moda ya que reviews muy altas o muy bajas podrían afectar el promedio
data2["review_scores_rating"]=data2["review_scores_rating"].fillna(0)
data2["review_scores_accuracy"]=data2["review_scores_accuracy"].fillna(0)
data2["review_scores_cleanliness"]=data2["review_scores_cleanliness"].fillna(0)
data2["review_scores_checkin"]=data2["review_scores_checkin"].fillna(0)
data2["review_scores_communication"]=data2["review_scores_communication"].fillna(0)
data2["review_scores_location"]=data2["review_scores_location"].fillna(0)
data2["review_scores_value"]=data2["review_scores_value"].fillna(0)

In [37]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
Length: 76, dtype: int64

In [38]:
#Sustituir valores nulos por un STRING en  concreto, 
# no se puede saber el tipo de licencia, se llena con NON specified
data2["license"] =data2["license"].fillna("Non specified")

In [39]:
#Sustituir valores nulos con promedio o media
# Ya que son valores numéricos, se usa el promedio
data2["reviews_per_month"]=data2["reviews_per_month"].fillna(round(data1["reviews_per_month"].mean(),1))

In [40]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                              0
listing_url                                     0
scrape_id                                       0
last_scraped                                    0
source                                          0
                                               ..
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
Length: 76, dtype: int64

In [41]:
#Convertir DataFrame a CSV
data2.to_csv("boston_sin_nulos.csv")