### Actividad 5.3

Ivanna Maldonado C.

In [451]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [452]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('BostonComplete.csv')
data["price"] = data["price"].replace('[\$,]', '', regex=True)
data["price"] = data["price"].astype(float)
data.head(2)

<>:3: SyntaxWarning: invalid escape sequence '\$'
<>:3: SyntaxWarning: invalid escape sequence '\$'
/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_45124/3316033828.py:3: SyntaxWarning: invalid escape sequence '\$'
  data["price"] = data["price"].replace('[\$,]', '', regex=True)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,https://www.airbnb.com/users/show/4804,Frank,2008-12-03,"Massachusetts, United States",My wife and I and grown children frequently oc...,within a day,75%,13%,t,https://a0.muscache.com/im/users/4804/profile_...,https://a0.muscache.com/im/users/4804/profile_...,East Boston,3,6,"['email', 'phone']",t,f,Neighborhood highlights,East Boston,NaN,42.36413,-71.02991,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Essentials"", ""Washer"", ""Patio or balcony"", ""...",125.0,29,1125,29,29,1125,1125,29.0,1125.0,NaN,t,0,0,0,262,2025-06-19,26,1,0,93,1,58,7250.0,2015-07-10,2024-08-09,4.96,5.00,4.96,5.00,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,https://www.airbnb.com/users/show/8229,Terry,2009-02-19,"Boston, MA","Relaxed, Easy going, Accommodating.",within an hour,100%,100%,t,https://a0.muscache.com/im/users/8229/profile_...,https://a0.muscache.com/im/users/8229/profile_...,Roxbury,12,15,"['email', 'phone']",t,t,Neighborhood highlights,Roxbury,NaN,42.32844,-71.09581,Entire guest suite,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Essentials"", ""Private entrance"", ""Washer"", ""...",142.0,3,90,1,3,1125,1125,3.0,1125.0,NaN,t,4,11,22,103,2025-06-19,137,13,1,103,10,78,11076.0,2009-03-21,2025-06-12,4.82,4.89,4.91,4.95,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69

In [453]:
#Corroboramos valores nulos
valores_nulos=data.isnull().mean()
valores_nulos

id                                              0.000000
listing_url                                     0.000000
scrape_id                                       0.000000
last_scraped                                    0.000000
source                                          0.000000
name                                            0.000000
description                                     0.009868
neighborhood_overview                           0.490351
picture_url                                     0.000000
host_id                                         0.000000
host_url                                        0.000000
host_name                                       0.000000
host_since                                      0.000000
host_location                                   0.202412
host_about                                      0.331360
host_response_time                              0.116447
host_response_rate                              0.116447
host_acceptance_rate                            0.106579
host_is_superhost                               0.038596
host_thumbnail_url                              0.000000
host_picture_url                                0.000000
host_neighbourhood                              0.026096
host_listings_count                             0.000000
host_total_listings_count                       0.000000
host_verifications                              0.000000
host_has_profile_pic                            0.000000
host_identity_verified                          0.000000
neighbourhood                                   0.490351
neighbourhood_cleansed                          0.000000
neighbourhood_group_cleansed                    1.000000
latitude                                        0.000000
longitude                                       0.000000
property_type                                   0.000000
room_type                                       0.000000
accommodates                                    0.000000
bathrooms                                       0.181798
bathrooms_text                                  0.000000
bedrooms                                        0.058991
beds                                            0.182895
amenities                                       0.000000
price                                           0.189693
minimum_nights                                  0.000000
maximum_nights                                  0.000000
minimum_minimum_nights                          0.000000
maximum_minimum_nights                          0.000000
minimum_maximum_nights                          0.000000
maximum_maximum_nights                          0.000000
minimum_nights_avg_ntm                          0.000000
maximum_nights_avg_ntm                          0.000000
calendar_updated                                1.000000
has_availability                                0.042982
availability_30                                 0.000000
availability_60                                 0.000000
availability_90                                 0.000000
availability_365                                0.000000
calendar_last_scraped                           0.000000
number_of_reviews                               0.000000
number_of_reviews_ltm                           0.000000
number_of_reviews_l30d                          0.000000
availability_eoy                                0.000000
number_of_reviews_ly                            0.000000
estimated_occupancy_l365d                       0.000000
estimated_revenue_l365d                         0.189693
first_review                                    0.233772
last_review                                     0.233772
review_scores_rating                            0.233772
review_scores_accuracy                          0.233991
review_scores_cleanliness                       0.233772
review_scores_checkin                           0.234211
review_scores_communication                     0.233772
review_scores_location                          0.234211
review_scores_value                             0.234211
license                                         0.342763
instant_bookable                                0.000000
calculated_host_listings_count                  0.000000
calculated_host_listings_count_entire_homes     0.000000
calculated_host_listings_count_private_rooms    0.000000
calculated_host_listings_count_shared_rooms     0.000000
reviews_per_month                               0.233772
dtype: float64

In [454]:
#Realizamos una copia del dataframe 
data1=data.copy()

In [455]:
#Eliminar columnas innecesarias
#Estas tres columnas están en su mayoría vacías, neighbourhood_overview no es tan relevante y está 49% vacía
data2= data1.drop(['neighborhood_overview', 'calendar_updated', 'neighbourhood_group_cleansed'], axis=1)
data2.head(2)

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,https://a0.muscache.com/pictures/24670/b2de044...,4804,https://www.airbnb.com/users/show/4804,Frank,2008-12-03,"Massachusetts, United States",My wife and I and grown children frequently oc...,within a day,75%,13%,t,https://a0.muscache.com/im/users/4804/profile_...,https://a0.muscache.com/im/users/4804/profile_...,East Boston,3,6,"['email', 'phone']",t,f,Neighborhood highlights,East Boston,42.36413,-71.02991,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Essentials"", ""Washer"", ""Patio or balcony"", ""...",125.0,29,1125,29,29,1125,1125,29.0,1125.0,t,0,0,0,262,2025-06-19,26,1,0,93,1,58,7250.0,2015-07-10,2024-08-09,4.96,5.00,4.96,5.00,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,https://a0.muscache.com/pictures/miso/Hosting-...,8229,https://www.airbnb.com/users/show/8229,Terry,2009-02-19,"Boston, MA","Relaxed, Easy going, Accommodating.",within an hour,100%,100%,t,https://a0.muscache.com/im/users/8229/profile_...,https://a0.muscache.com/im/users/8229/profile_...,Roxbury,12,15,"['email', 'phone']",t,t,Neighborhood highlights,Roxbury,42.32844,-71.09581,Entire guest suite,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Essentials"", ""Private entrance"", ""Washer"", ""...",142.0,3,90,1,3,1125,1125,3.0,1125.0,t,4,11,22,103,2025-06-19,137,13,1,103,10,78,11076.0,2009-03-21,2025-06-12,4.82,4.89,4.91,4.95,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69

In [456]:
#Sustituir valores nulos por un STRING en  concreto 
#Rellenamos con NO DESCRIPTION porque no hay forma de saber la descripción de una propiedad
data2["description"] =data2["description"].fillna("No description")

In [457]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                    923
host_about                                      1511
host_response_time                               531
host_response_rate                               531
host_acceptance_rate                             486
host_is_superhost                                176
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [458]:
#Sustituir valores nulos por un STRING en  concreto 
#Rellenamos con Boston, MA. porque la mayoría de los hosts son de ahí y sería el "promedio" de los datos.
data2["host_location"] =data2["host_location"].fillna("Boston, MA")

In [459]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                      1511
host_response_time                               531
host_response_rate                               531
host_acceptance_rate                             486
host_is_superhost                                176
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [460]:
#Sustituir valores nulos por un STRING en  concreto 
#Rellenamos con No INFO porque no podemos saber los datos de los hosts.
data2["host_about"] =data2["host_about"].fillna("No information")

In [461]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                               531
host_response_rate                               531
host_acceptance_rate                             486
host_is_superhost                                176
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [462]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
#Filtro por columnas
data2["host_response_time"] =data2["host_response_time"].fillna(method="ffill")

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_45124/1220790007.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["host_response_time"] =data2["host_response_time"].fillna(method="ffill")

In [463]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                               531
host_acceptance_rate                             486
host_is_superhost                                176
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [464]:
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
# Como son %, es muy complicado quitar el signo y cambiar de string a int.
data2["host_response_rate"] =data2["host_response_rate"].fillna(method="bfill")

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_45124/3542546518.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["host_response_rate"] =data2["host_response_rate"].fillna(method="bfill")

In [465]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                             486
host_is_superhost                                176
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [466]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
#Filtro por columnas
data2["host_acceptance_rate"] =data2["host_acceptance_rate"].fillna(method="ffill")

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_45124/3225591725.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["host_acceptance_rate"] =data2["host_acceptance_rate"].fillna(method="ffill")

In [467]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                176
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [468]:
#Sustituir valores nulos por un STRING en  concreto 
#Se sustituye con el tipo de host más común
data2["host_is_superhost"] =data2["host_is_superhost"].fillna("f")

In [469]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [470]:
#Sustituir valores nulos por un STRING en  concreto 
#El vecindario del host no es tan importante, por lo que se rellena con NON SPECIFIED
data2["host_neighbourhood"] =data2["host_neighbourhood"].fillna("Non specified")

In [471]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                                 0
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [472]:
#Sustituir valores nulos por un STRING en  concreto 
#Se sustituye con el unico string que se encuentra en la base de datos
data2["neighbourhood"] =data2["neighbourhood"].fillna("Neighbourhood highlights")

In [473]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                                 0
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                      0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [474]:
#Sustituir valores nulos con promedio o media
data2["bathrooms"]=data2["bathrooms"].fillna("0")

In [475]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                                 0
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                      0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [476]:
#Sustituir valores nulos con promedio o media
data2["bedrooms"]=data2["bedrooms"].fillna(round(data1["bedrooms"].mean(),1))

In [477]:
#Sustituir valores nulos con promedio o media
data2["beds"]=data2["beds"].fillna(round(data1["beds"].mean(),1))

In [478]:
#Sustituir valores nulos con promedio o media
#Al inicio quité el signo de $ de price, así que puedo usar mean para rellenar
data2["price"]=data2["price"].fillna(round(data1["price"].mean(),1))

In [479]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                                 0
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                      0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                     0
bedrooms                                           0
beds                                               0
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [480]:
#Sustituir valores nulos por un STRING en  concreto, en su mayoría es TRUE
data2["has_availability"] =data2["has_availability"].fillna("t")

In [481]:
#Sustituir valores nulos con promedio o media
data2["estimated_revenue_l365d"]=data2["estimated_revenue_l365d"].fillna(round(data1["estimated_revenue_l365d"].mean(),1))

In [482]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                                 0
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                      0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                     0
bedrooms                                           0
beds                                               0
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                            0
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [483]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
data2["first_review"] =data2["first_review"].fillna(method="ffill")

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_45124/2007489826.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["first_review"] =data2["first_review"].fillna(method="ffill")

In [484]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
data2["last_review"] =data2["last_review"].fillna(method="ffill")

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_45124/542261576.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["last_review"] =data2["last_review"].fillna(method="ffill")

In [485]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                                 0
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                      0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                     0
bedrooms                                           0
beds                                               0
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                            0
first_review                                       0
last_review                                        0
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [486]:
#Sustituir valores nulos con promedio o media
#Las últimas variables son todas numéricas, así que decidí usar la moda ya que reviews muy altas o muy bajas podrían afectar el promedio
data2["review_scores_rating"]=data2["review_scores_rating"].fillna(0)
data2["review_scores_accuracy"]=data2["review_scores_accuracy"].fillna(0)
data2["review_scores_cleanliness"]=data2["review_scores_cleanliness"].fillna(0)
data2["review_scores_checkin"]=data2["review_scores_checkin"].fillna(0)
data2["review_scores_communication"]=data2["review_scores_communication"].fillna(0)
data2["review_scores_location"]=data2["review_scores_location"].fillna(0)
data2["review_scores_value"]=data2["review_scores_value"].fillna(0)

In [487]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                                 0
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                      0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                     0
bedrooms                                           0
beds                                               0
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                            0
first_review                                       0
last_review                                        0
review_scores_rating                               0
review_scores_accuracy                             0
review_scores_cleanliness                          0
review_scores_checkin                              0
review_scores_communication                        0
review_scores_location                             0
review_scores_value                                0
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [488]:
#Sustituir valores nulos por un STRING en  concreto, 
# no se puede saber el tipo de licencia, se llena con NON specified
data2["license"] =data2["license"].fillna("Non specified")

In [489]:
#Sustituir valores nulos con promedio o media
# Ya que son valores numéricos, se usa el promedio
data2["reviews_per_month"]=data2["reviews_per_month"].fillna(round(data1["reviews_per_month"].mean(),1))

In [490]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                              0
listing_url                                     0
scrape_id                                       0
last_scraped                                    0
source                                          0
name                                            0
description                                     0
picture_url                                     0
host_id                                         0
host_url                                        0
host_name                                       0
host_since                                      0
host_location                                   0
host_about                                      0
host_response_time                              0
host_response_rate                              0
host_acceptance_rate                            0
host_is_superhost                               0
host_thumbnail_url                              0
host_picture_url                                0
host_neighbourhood                              0
host_listings_count                             0
host_total_listings_count                       0
host_verifications                              0
host_has_profile_pic                            0
host_identity_verified                          0
neighbourhood                                   0
neighbourhood_cleansed                          0
latitude                                        0
longitude                                       0
property_type                                   0
room_type                                       0
accommodates                                    0
bathrooms                                       0
bathrooms_text                                  0
bedrooms                                        0
beds                                            0
amenities                                       0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
minimum_minimum_nights                          0
maximum_minimum_nights                          0
minimum_maximum_nights                          0
maximum_maximum_nights                          0
minimum_nights_avg_ntm                          0
maximum_nights_avg_ntm                          0
has_availability                                0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
calendar_last_scraped                           0
number_of_reviews                               0
number_of_reviews_ltm                           0
number_of_reviews_l30d                          0
availability_eoy                                0
number_of_reviews_ly                            0
estimated_occupancy_l365d                       0
estimated_revenue_l365d                         0
first_review                                    0
last_review                                     0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
license                                         0
instant_bookable                                0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
dtype: int64

In [491]:
#Convertir DataFrame a CSV
data2.to_csv("boston_sin_nulos.csv")