### Actividad 5.2

Ivanna Maldonado C.

In [73]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [74]:
#Carga desde un archivo .xlsx sin indice
data = pd.read_excel('Gastos y costos 20-23.xlsx')
data.head(5)

,CALOR Y CONTROL S.A DE C.V,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,GASTO,10418041.599138,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,DEDUCCIONES 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IVA,1597941.439462,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RET IVA,198890.4,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RET ISR,66039.89,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1

In [75]:
#Eliminar primera fila o filas innecesarias
#Se eliminan pora poder tener los datos correctos
data1= pd.read_excel('Gastos y costos 20-23.xlsx', skiprows=5)
data1.head(5)

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,NaN,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.00,2248.28,0.0,0.0,2248.28,16300.00,I,Vigente,NaN,14051.72
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente,NaN,0.00
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,195.00,31.20,0.0,0.0,226.20,226.20,I,Vigente,NaN,0.00
3,2020-01-01,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,NaN,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1.0,10694.25,1711.08,0.0,0.0,12405.33,12405.33,I,Vigente,NaN,0.00
4,2020-01-01,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,NaN,Pago,1.0,0.00,NaN,0.0,0.0,0.00,0.00,P,Vigente,NaN,0.00

In [76]:
valores_nulos=data1.isnull().mean()
valores_nulos

FECHA          0.000000
FOLIO          0.056553
UUID           0.000000
RFC            0.000000
PROVEEDOR      0.000000
TIPO GASTO     0.000000
GASTO          0.748654
DESCRIPCION    0.000000
TC             0.116996
IMPORTE        0.010174
IVA            0.080192
RET ISR        0.000000
RET IVA        0.000000
TOTAL MX       0.000000
TOTAL SAT      0.000000
TIPO           0.000299
STATUS         0.000000
POLIZA         0.993716
Columna1       0.000000
dtype: float64

In [77]:
#Realizamos una copia del dataframe 
data2=data1.copy()

In [78]:
#Eliminar columnas innecesarias
#Estas dos columnas están en su mayoría vacías, por lo que es mejor eliminarlas que rellenarlas.
data2= data1.drop(['POLIZA', 'Columna1'], axis=1)
data2.head(2)

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,NaN,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.0,2248.28,0.0,0.0,2248.28,16300.0,I,Vigente
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,490.0,78.40,0.0,0.0,568.40,568.4,I,Vigente

In [79]:
valores_nulos=data2.isnull().sum()
valores_nulos

FECHA             0
FOLIO           189
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO          2502
DESCRIPCION       0
TC              391
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
dtype: int64

In [80]:
#Sustituir valores nulos por un STRING en  concreto 
#Ya que los valores nulos son el más de la mitad del df, se sustituye con no folio para no eliminar la columna completa. 
#No podemos inventar folios individuales, por lo que se escribe NO FOLIO
data2["FOLIO"] =data2["FOLIO"].fillna("No folio")

In [81]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

FECHA             0
FOLIO             0
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO          2502
DESCRIPCION       0
TC              391
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
dtype: int64

In [82]:
#Sustituir valores nulos por un STRING en  concreto 
#Se sustituye con el tipo de gasto más común
data2["GASTO"] =data2["GASTO"].fillna("COMPRA")

In [83]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

FECHA            0
FOLIO            0
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
GASTO            0
DESCRIPCION      0
TC             391
IMPORTE         34
IVA            268
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             1
STATUS           0
dtype: int64

In [84]:
#Sustituir valores nulos por un valor numérico en  concreto 
#Ya que TC tiene la mayoría de los datos "1", 
data2["TC"]= data2["TC"].fillna(1) 
data2

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,COMPRA,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.00,2248.28,0.0,0.0,2248.28,16300.00,I,Vigente
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMPRA,COMISION COBRADA,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMPRA,COMISION COBRADA,1.0,195.00,31.20,0.0,0.0,226.20,226.20,I,Vigente
3,2020-01-01,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,COMPRA,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1.0,10694.25,1711.08,0.0,0.0,12405.33,12405.33,I,Vigente
4,2020-01-01,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,COMPRA,Pago,1.0,0.00,NaN,0.0,0.0,0.00,0.00,P,Vigente
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3337,2020-12-01,125834,80BCB1D8-673F-495B-9C2A-4AC9F9CB38E5,SQS110113MU0,SERVICIO QUINTANA SUR S.A DE C.V,COMBUSTIBLE,G VTA,32011 MAGNA,1.0,129.79,20.21,0.0,0.0,150.00,150.00,I,Vigente
3338,2020-12-01,37652,D4C7C1FB-03A7-4046-A2BD-03EBE7DA861E,PSQ790724C90,"CIA. PERIODISTICA DEL SOL DE QUERETARO, S.A. D...",PUBLICIDAD,G VTA,82101504-PUBLICIDAD EN PERIODICOSCALOR Y CONTROL,1.0,2284.80,365.57,0.0,0.0,2650.37,2650.37,I,Vigente
3339,2020-12-01,160,FFCEE7D4-1F38-4D44-BE02-EB042DAACEE7,SQX981027RY5,"SUPER Q, S. A. DE C. V.",ALIMENTOS,G VTA,REF VICTORIA GROSELLA 3 LT PET NR,1.0,163.79,26.21,0.0,0.0,190.00,190.00,I,Vigente
3340,2020-12-01,634875,8DFF4F01-2F8B-4085-B116-05A314108B02,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,G FINA,COMISIONES E INTERESES,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente
3341,2020-12-01,1044477,F18225D6-4024-4F03-A15A-D18917386D59,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,COMBUSTIBLE,G VTA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,1.0,14889.29,0.00,0.0,0.0,14889.29,14889.29,I,Vigente

In [85]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

FECHA            0
FOLIO            0
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
GASTO            0
DESCRIPCION      0
TC               0
IMPORTE         34
IVA            268
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             1
STATUS           0
dtype: int64

In [86]:
#Sustituir valores nulos con promedio o media
data2["IMPORTE"]=data2["IMPORTE"].fillna(round(data1["IMPORTE"].mean(),1))

In [87]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

FECHA            0
FOLIO            0
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
GASTO            0
DESCRIPCION      0
TC               0
IMPORTE          0
IVA            268
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             1
STATUS           0
dtype: int64

In [88]:
#Sustituir valores nulos con promedio o media
data2["IVA"]=data2["IVA"].fillna(round(data1["IVA"].mean(),1))

In [89]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

FECHA          0
FOLIO          0
UUID           0
RFC            0
PROVEEDOR      0
TIPO GASTO     0
GASTO          0
DESCRIPCION    0
TC             0
IMPORTE        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
TIPO           1
STATUS         0
dtype: int64

In [92]:
#Sustituir valores nulos por un valor numérico en  concreto 
#El valor faltante es un combustible, los demás combustibles son del tipo I, así que se rellena con ese valor.
data2["TIPO"]= data2["TIPO"].fillna('I') 
data2.head(2)

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,COMPRA,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.0,2248.28,0.0,0.0,2248.28,16300.0,I,Vigente
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMPRA,COMISION COBRADA,1.0,490.0,78.40,0.0,0.0,568.40,568.4,I,Vigente

In [95]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

FECHA          0
FOLIO          0
UUID           0
RFC            0
PROVEEDOR      0
TIPO GASTO     0
GASTO          0
DESCRIPCION    0
TC             0
IMPORTE        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
TIPO           0
STATUS         0
dtype: int64

In [97]:
#Convertir DataFrame a CSV
data2.to_csv("gastos2023_sin_nulos.csv")