#### Actividad 7: Evaluación

Ivanna Maldonado Cervantes

In [486]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [487]:
#Carga desde un archivo .csv sin indice
df = pd.read_csv('cuentas_credicel.csv', encoding='latin1')
df.head()

/var/folders/vv/zkrntk9d6sjc4rn30m21zp2w0000gp/T/ipykernel_26616/4135459357.py:2: DtypeWarning: Columns (26,31,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('cuentas_credicel.csv', encoding='latin1')

,folio,tag,folio_solicitud,fecha,marca,modelo,plazo,precio,enganche,descuento,...,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,3,HDNAWQ3A,30,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,...,NaN,0.0,0.0,0,0.0,0,NaN,NaN,26.0,NaN
1,4,M418YNR4,33,12/11/2021 19:15,MOTOROLA,LTE XT2097-12 E7I POWER Azul,13S,2999.0,1050.0,0.0,...,NaN,0.0,0.0,0,0.0,0,NaN,NaN,13.0,NaN
2,5,SZ7V3NZT,37,13/11/2021 14:13,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,74,NaN,NaN
3,6,9I08UIQZ,38,13/11/2021 15:45,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,NaN,0.0,0.0,0,0.0,0,NaN,NaN,13.0,NaN
4,7,JMF4LKYU,44,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,...,0.0,0.0,0.0,NaN,NaN,74,NaN,NaN,NaN,NaN

In [488]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 37 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   folio               22735 non-null  int64
 1   tag                 22735 non-null  object
 2   folio_solicitud     22735 non-null  int64
 3   fecha               22735 non-null  object
 4   marca               22735 non-null  object
 5   modelo              22735 non-null  object
 6   plazo               22735 non-null  object
 7   precio              22735 non-null  float64
 8   enganche            22735 non-null  float64
 9   descuento           22735 non-null  float64
 10  semana              22735 non-null  int64
 11  monto_financiado    22735 non-null  float64
 12  costo_total         22735 non-null  int64
 13  monto_accesorios    22735 non-null  float64
 14  agente_venta        22735 non-null  object
 15  dis_venta           22735 non-null  object
 16  status              22735 non-null  int64
 17  fraude              22735 non-null  int64
 18  empresa             22722 non-null  object
 19  inversion           22735 non-null  int64
 20  pagos_realizados    22735 non-null  int64
 21  reautorizacion      22735 non-null  int64
 22  fecha_ultimo_pago   19379 non-null  object
 23  fecha_pago_proximo  19379 non-null  object
 24  status_cuenta       18538 non-null  object
 25  puntos              19140 non-null  float64
 26  riesgo              20262 non-null  object
 27  porc_enganche       20262 non-null  float64
 28  porc_tasa           22735 non-null  float64
 29  score_buro          22735 non-null  float64
 30  razones_buro        18230 non-null  object
 31  semana_actual       18230 non-null  object
 32  codigo_postal       22050 non-null  object
 33  Unnamed: 33         859 non-null    object
 34  Unnamed: 34         1203 non-null   object
 35  Unnamed: 35         2473 non-null   float64
 36  Unnamed: 36         1 non-null      float64
dtypes: float64(11), int64(9), object(17)
memory usage: 6.4+ MB

#### Filtros

In [489]:
#Todas la columnas menos 'folio', 'folio_solicitud', 'unnamed:33', 'unnamed:34', 'unnamed:35', 'unnamed:36'
df = df.drop(columns=['folio', 'folio_solicitud', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36'])
df

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,81,1169.0,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
1,M418YNR4,12/11/2021 19:15,MOTOROLA,LTE XT2097-12 E7I POWER Azul,13S,2999.0,1050.0,0.0,225,1949.0,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
2,SZ7V3NZT,13/11/2021 14:13,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,170,1469.0,...,NaN,NaN,NaN,Cancelado,0.00,0.00,0.0,0,0.0,NaN
3,9I08UIQZ,13/11/2021 15:45,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,170,1469.0,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,178,3224.0,...,12/03/2022 00:00,Mora,0.0,0,0.00,0.00,0.0,NaN,NaN,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22730,92KQVRIX,18/04/2023 18:45,Motorola,Moto E13,26S,3349.0,297.0,0.0,211,3052.0,...,25/04/2023 00:00,NaN,NaN,10.0,27.40,-1.13,0.0,0,"K0,J0,D8,E2",0
22731,NWB2EA8J,18/04/2023 18:46,Motorola,Moto E22i,26S,4100.0,1209.0,0.0,200,2891.0,...,25/04/2023 00:00,NaN,NaN,9.0,19.00,7.48,0.0,0,"K0,J0,D8,E2",0
22732,VDTRJ2W6,18/04/2023 18:47,Samsung,A13,26S,4849.0,1152.0,0.0,256,3697.0,...,25/04/2023 00:00,NaN,NaN,11.0,26.65,0.75,0.0,0,"K0,D7,F7,D8",0
22733,PETLF56C,18/04/2023 18:49,Samsung,A53 5G,39S,9799.0,2799.0,0.0,386,7000.0,...,25/04/2023 00:00,NaN,NaN,14.0,-17.35,-0.14,0.0,0,"J0,G1,E0,E2",0
22734,2CI4N2WS,18/04/2023 18:49,Samsung,A22 5G,26S,5399.0,1086.0,0.0,299,4313.0,...,25/04/2023 00:00,NaN,NaN,12.0,21.80,-2.88,0.0,0,C2,0

In [490]:
#Todas las filas: "múltiplos de 4" (0, 4, 8, 12...)
filtro1 = df.iloc[::4]
filtro1

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.00,780.0,0.0,81,1169.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.00,1075.0,0.0,178,3224.00,...,12/03/2022 00:00,Mora,0.0,0,0.00,0.00,0.0,NaN,NaN,74
8,5SDZN7O1,14/11/2021 13:34,KODAK,LTE SEREN D60LX Azul,26S,2889.00,1000.0,0.0,131,1889.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.00,1750.0,0.0,363,5249.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.00,2000.0,0.0,92,799.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22716,AN6FJ9K0,18/04/2023 16:43,Alcatel,5030A 1SE,26S,4499.00,1522.0,0.0,229,3306.00,...,25/04/2023 00:00,NaN,NaN,11.0,32.00,9.84,0.0,0,"K0,J0,E2,D8",0
22720,WI1NMWI1,18/04/2023 17:04,MOTOROLA,4G XT2239-17 E22I Gris Kit,26S,3508.83,774.0,0.0,197,2734.83,...,25/04/2023 00:00,NaN,NaN,11.0,6.85,1.05,0.0,0,"K0,J0,E2,M1",0
22724,RTBMD1Z2,18/04/2023 17:15,Motorola,Moto E32,39S,3799.00,726.0,0.0,169,3073.00,...,25/04/2023 00:00,NaN,NaN,12.0,1.75,-0.90,0.0,0,"D7,F7,J0,E2",0
22728,X4AXNZBG,18/04/2023 17:33,Motorola,Moto E22i,39S,3499.00,354.0,0.0,173,3145.00,...,25/04/2023 00:00,NaN,NaN,11.0,26.35,0.13,0.0,0,"K0,J0,D7,E2",0
22732,VDTRJ2W6,18/04/2023 18:47,Samsung,A13,26S,4849.00,1152.0,0.0,256,3697.00,...,25/04/2023 00:00,NaN,NaN,11.0,26.65,0.75,0.0,0,"K0,D7,F7,D8",0

In [491]:
# Todos los registros cuya marca sea igual a: "ALCATEL", "MOTOROLA", "NOKIA", "ZTE" "SAMSUNG"
filtro2 = filtro1[filtro1['marca'].isin(['ALCATEL', 'MOTOROLA', 'NOKIA', 'ZTE', 'SAMSUNG'])]
filtro2

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.00,780.0,0.0,81,1169.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.00,1075.0,0.0,178,3224.00,...,12/03/2022 00:00,Mora,0.0,0,0.00,0.00,0.0,NaN,NaN,74
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.00,1750.0,0.0,363,5249.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.00,2000.0,0.0,92,799.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
20,C9LVYPGM,17/11/2021 16:28,ZTE,LTE A5 2020 64GB R Azul,26S,2499.00,625.0,0.0,130,1874.00,...,17/03/2022 00:00,Mora,0.0,0,0.00,0.00,0.0,NaN,NaN,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22684,3GUQ4FSQ,18/04/2023 12:39,SAMSUNG,GALAXY A14 5G 4+128GB NEGRO B,26S,6158.88,1348.0,0.0,366,5074.88,...,25/04/2023 00:00,NaN,NaN,12.0,5.55,0.89,0.0,0,"K0,J0,E2,D2",0
22688,C1KS51OF,18/04/2023 13:13,MOTOROLA,MOTO E22I 2+64GB GRIS B,26S,3508.83,866.0,0.0,206,2861.83,...,25/04/2023 00:00,NaN,NaN,12.0,25.10,1.67,0.0,0,C2,0
22696,PVT930EN,18/04/2023 14:12,MOTOROLA,MOTO G71 5G,26S,6000.00,1508.0,0.0,311,4492.00,...,25/04/2023 00:00,NaN,NaN,11.0,27.00,2.13,0.0,0,"K0,J0,D7,E2",0
22704,BQKFBAAX,18/04/2023 15:10,ZTE,BLADE A3 2020 Rojo,26S,2004.82,233.0,0.0,128,1771.82,...,25/04/2023 00:00,NaN,NaN,9.0,16.85,1.60,0.0,0,"K0,J0,E2,M1",0
22720,WI1NMWI1,18/04/2023 17:04,MOTOROLA,4G XT2239-17 E22I Gris Kit,26S,3508.83,774.0,0.0,197,2734.83,...,25/04/2023 00:00,NaN,NaN,11.0,6.85,1.05,0.0,0,"K0,J0,E2,M1",0

In [492]:
# Todos los registros cuyo enganche se encuentre entre: "$500 y $2000"
filtro3 = filtro2[(filtro2['enganche']>= 500)&(filtro2['enganche']<=2000)]
filtro3

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.00,780.0,0.0,81,1169.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.00,1075.0,0.0,178,3224.00,...,12/03/2022 00:00,Mora,0.0,0,0.00,0.00,0.0,NaN,NaN,74
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.00,1750.0,0.0,363,5249.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.00,2000.0,0.0,92,799.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
20,C9LVYPGM,17/11/2021 16:28,ZTE,LTE A5 2020 64GB R Azul,26S,2499.00,625.0,0.0,130,1874.00,...,17/03/2022 00:00,Mora,0.0,0,0.00,0.00,0.0,NaN,NaN,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22680,511U4ZDH,18/04/2023 11:53,SAMSUNG,4G SM-A045M GALAXY A04 Verde Kit,26S,3157.83,525.0,0.0,190,2632.83,...,25/04/2023 00:00,NaN,NaN,14.0,-23.00,0.64,0.0,0,"G1,E0,E2,E4",0
22684,3GUQ4FSQ,18/04/2023 12:39,SAMSUNG,GALAXY A14 5G 4+128GB NEGRO B,26S,6158.88,1348.0,0.0,366,5074.88,...,25/04/2023 00:00,NaN,NaN,12.0,5.55,0.89,0.0,0,"K0,J0,E2,D2",0
22688,C1KS51OF,18/04/2023 13:13,MOTOROLA,MOTO E22I 2+64GB GRIS B,26S,3508.83,866.0,0.0,206,2861.83,...,25/04/2023 00:00,NaN,NaN,12.0,25.10,1.67,0.0,0,C2,0
22696,PVT930EN,18/04/2023 14:12,MOTOROLA,MOTO G71 5G,26S,6000.00,1508.0,0.0,311,4492.00,...,25/04/2023 00:00,NaN,NaN,11.0,27.00,2.13,0.0,0,"K0,J0,D7,E2",0
22720,WI1NMWI1,18/04/2023 17:04,MOTOROLA,4G XT2239-17 E22I Gris Kit,26S,3508.83,774.0,0.0,197,2734.83,...,25/04/2023 00:00,NaN,NaN,11.0,6.85,1.05,0.0,0,"K0,J0,E2,M1",0

In [493]:
# Todos los registros cuya categoría en riesgo: NO sea "Cancelado" ni "Fraude"
filtro4 = filtro3[~(filtro3['riesgo'].isin(['Cancelado', 'Fraude']))]
filtro4

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
0,HDNAWQ3A,12/11/2021 19:00,ZTE,Blade A3 2020 RO B,26S,1949.00,780.0,0.0,81,1169.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
4,JMF4LKYU,13/11/2021 16:10,MOTOROLA,G10 B,39S,4299.00,1075.0,0.0,178,3224.00,...,12/03/2022 00:00,Mora,0.0,0,0.00,0.00,0.0,NaN,NaN,74
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.00,1750.0,0.0,363,5249.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.00,2000.0,0.0,92,799.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
20,C9LVYPGM,17/11/2021 16:28,ZTE,LTE A5 2020 64GB R Azul,26S,2499.00,625.0,0.0,130,1874.00,...,17/03/2022 00:00,Mora,0.0,0,0.00,0.00,0.0,NaN,NaN,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22680,511U4ZDH,18/04/2023 11:53,SAMSUNG,4G SM-A045M GALAXY A04 Verde Kit,26S,3157.83,525.0,0.0,190,2632.83,...,25/04/2023 00:00,NaN,NaN,14.0,-23.00,0.64,0.0,0,"G1,E0,E2,E4",0
22684,3GUQ4FSQ,18/04/2023 12:39,SAMSUNG,GALAXY A14 5G 4+128GB NEGRO B,26S,6158.88,1348.0,0.0,366,5074.88,...,25/04/2023 00:00,NaN,NaN,12.0,5.55,0.89,0.0,0,"K0,J0,E2,D2",0
22688,C1KS51OF,18/04/2023 13:13,MOTOROLA,MOTO E22I 2+64GB GRIS B,26S,3508.83,866.0,0.0,206,2861.83,...,25/04/2023 00:00,NaN,NaN,12.0,25.10,1.67,0.0,0,C2,0
22696,PVT930EN,18/04/2023 14:12,MOTOROLA,MOTO G71 5G,26S,6000.00,1508.0,0.0,311,4492.00,...,25/04/2023 00:00,NaN,NaN,11.0,27.00,2.13,0.0,0,"K0,J0,D7,E2",0
22720,WI1NMWI1,18/04/2023 17:04,MOTOROLA,4G XT2239-17 E22I Gris Kit,26S,3508.83,774.0,0.0,197,2734.83,...,25/04/2023 00:00,NaN,NaN,11.0,6.85,1.05,0.0,0,"K0,J0,E2,M1",0

In [494]:
# Todos los registros cuya fecha : Sea posterior a "15/11/2021"
filtro5 = filtro4[filtro4['fecha'] > "15/11/2021"]
filtro5

,tag,fecha,marca,modelo,plazo,precio,enganche,descuento,semana,monto_financiado,...,fecha_pago_proximo,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal
12,BFXA3OX9,15/11/2021 12:10,MOTOROLA,MOTO G60 6+128 GB GRIS B,26S,6999.00,1750.0,0.0,363,5249.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
16,X53IWV9M,16/11/2021 13:35,ALCATEL,5007A 1V 2020 Negro,13S,2799.00,2000.0,0.0,92,799.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
20,C9LVYPGM,17/11/2021 16:28,ZTE,LTE A5 2020 64GB R Azul,26S,2499.00,625.0,0.0,130,1874.00,...,17/03/2022 00:00,Mora,0.0,0,0.00,0.00,0.0,NaN,NaN,74
24,BWRZ9ZRG,20/11/2021 14:00,MOTOROLA,MOTOROLA LTE XT2053-5 E6I Gris,13S,2999.00,900.0,0.0,242,2099.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
28,74DZR6G2,23/11/2021 15:17,MOTOROLA,LTE XT2097-12 E7I POWER Naranja,26S,3299.00,990.0,0.0,160,2309.00,...,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22680,511U4ZDH,18/04/2023 11:53,SAMSUNG,4G SM-A045M GALAXY A04 Verde Kit,26S,3157.83,525.0,0.0,190,2632.83,...,25/04/2023 00:00,NaN,NaN,14.0,-23.00,0.64,0.0,0,"G1,E0,E2,E4",0
22684,3GUQ4FSQ,18/04/2023 12:39,SAMSUNG,GALAXY A14 5G 4+128GB NEGRO B,26S,6158.88,1348.0,0.0,366,5074.88,...,25/04/2023 00:00,NaN,NaN,12.0,5.55,0.89,0.0,0,"K0,J0,E2,D2",0
22688,C1KS51OF,18/04/2023 13:13,MOTOROLA,MOTO E22I 2+64GB GRIS B,26S,3508.83,866.0,0.0,206,2861.83,...,25/04/2023 00:00,NaN,NaN,12.0,25.10,1.67,0.0,0,C2,0
22696,PVT930EN,18/04/2023 14:12,MOTOROLA,MOTO G71 5G,26S,6000.00,1508.0,0.0,311,4492.00,...,25/04/2023 00:00,NaN,NaN,11.0,27.00,2.13,0.0,0,"K0,J0,D7,E2",0
22720,WI1NMWI1,18/04/2023 17:04,MOTOROLA,4G XT2239-17 E22I Gris Kit,26S,3508.83,774.0,0.0,197,2734.83,...,25/04/2023 00:00,NaN,NaN,11.0,6.85,1.05,0.0,0,"K0,J0,E2,M1",0

In [495]:
#Convertir archivos filtrados a CSV
filtro5.to_csv("Evaluación_3.csv")