Ivanna Maldonado Cervantes

In [37]:
#Importamos las librerias necesarias
import pandas as pd
import numpy as np
import os
import Act8_Ivanna as act

In [38]:
#Se realiza el llamado a la función "cargar_dataset" para leer el archivo
df_csv=act.cargar_dataset('listingsBoston.csv')

***Función de Limpieza de Valores Nulos***

In [39]:
pd.set_option("display.max_rows", None) # muestra todas las filas  #formato

In [40]:
# Visualizamos todos los valores nulos del datafranme orginal
df_csv.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                       45
neighborhood_overview                           2236
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                    923
host_about                                      1511
host_response_time                               531
host_response_rate                               531
host_acceptance_rate                             486
host_is_superhost                                176
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                    4560
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
calendar_updated                                4560
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                    1066
last_review                                     1066
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [41]:
# Llamamos a las funciones una por una del archivo py 
df_ffill = act.ffill_df(df_csv)
df_ffill.head(3)

/Users/hijos/Desktop/Analitica Prof/Prof. Alfredo/08_examen/Act8_Ivanna.py:29: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  return df.fillna(method="ffill")

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69
2,6695,https://www.airbnb.com/rooms/6695,20250619031426,2025-06-19,city scrape,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Comfortable, Fully Equipped private apartment...","Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/38ac4797-e7a4...,8229,...,4.94,4.53,4.72,STR-491702,f,11,11,0,0,0.72

In [42]:
# Comprobamos que se haya realizado lo indicado en la función.
df_ffill.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
neighborhood_overview                              0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                                 0
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                      0
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                    4560
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                     0
bedrooms                                           0
beds                                               0
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
calendar_updated                                4560
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                            0
first_review                                       0
last_review                                        0
review_scores_rating                               0
review_scores_accuracy                             0
review_scores_cleanliness                          0
review_scores_checkin                              0
review_scores_communication                        0
review_scores_location                             0
review_scores_value                                0
license                                            1
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                                  0
dtype: int64

In [43]:
df_bfill= act.bfill_df(df_csv)
df_bfill.head(3)

/Users/hijos/Desktop/Analitica Prof/Prof. Alfredo/08_examen/Act8_Ivanna.py:34: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  return df.fillna(method="bfill")

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,STR-490093,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69
2,6695,https://www.airbnb.com/rooms/6695,20250619031426,2025-06-19,city scrape,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Comfortable, Fully Equipped private apartment...","Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/38ac4797-e7a4...,8229,...,4.94,4.53,4.72,STR-491702,f,11,11,0,0,0.72

In [44]:
df_bfill.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
neighborhood_overview                              3
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                                 0
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                      3
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                    4560
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                     0
bedrooms                                           0
beds                                               0
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
calendar_updated                                4560
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                            0
first_review                                       6
last_review                                        6
review_scores_rating                               6
review_scores_accuracy                             6
review_scores_cleanliness                          6
review_scores_checkin                              6
review_scores_communication                        6
review_scores_location                             6
review_scores_value                                6
license                                            0
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                                  6
dtype: int64

In [45]:
df_str= act.fillna_string(df_csv)
df_str.tail()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
4555,1442936143734248350,https://www.airbnb.com/rooms/1442936143734248350,20250619031426,2025-06-19,city scrape,"2 level, 2 bed with office in Back Bay",Sin Dato,Step outside to immerse yourself in the quinte...,https://a0.muscache.com/pictures/prohost-api/H...,250399091,...,NaN,NaN,NaN,Sin Dato,f,7,7,0,0,NaN
4556,1442940477243281647,https://www.airbnb.com/rooms/1442940477243281647,20250619031426,2025-06-19,city scrape,"Sunny 2BR w/ Office, Near Copley & Shopping","Stay at The Harbor Suite, a chic 2BR loft in B...",* Shopping & Dining: Steps from Newbury Street...,https://a0.muscache.com/pictures/prohost-api/H...,250399091,...,NaN,NaN,NaN,Exempt: This listing is a unit used for furnis...,f,7,7,0,0,NaN
4557,1445146141923468353,https://www.airbnb.com/rooms/1445146141923468353,20250619031426,2025-06-19,city scrape,A tree house like room in Jamaica Plain,Take it easy at this unique and tranquil getaway.,Sin Dato,https://a0.muscache.com/pictures/hosting/Hosti...,5480536,...,NaN,NaN,NaN,STR-598354,f,2,0,2,0,NaN
4558,1445761247286385772,https://www.airbnb.com/rooms/1445761247286385772,20250619031426,2025-06-19,city scrape,NQ East Boston 3 Bdrm,This unique place has a style all its own.,Sin Dato,https://a0.muscache.com/pictures/hosting/Hosti...,699041704,...,NaN,NaN,NaN,STR-546284,t,3,3,0,0,NaN
4559,1445867715555794708,https://www.airbnb.com/rooms/1445867715555794708,20250619031426,2025-06-19,city scrape,Stylish Boston Getaway Near Arboretum & T Stat...,Discover the very best of Boston from the comf...,Sin Dato,https://a0.muscache.com/pictures/miso/Hosting-...,181205324,...,NaN,NaN,NaN,STR-593018,t,1,1,0,0,NaN

In [46]:
df_str.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                        0
neighborhood_overview                              0
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      0
host_about                                         0
host_response_time                                 0
host_response_rate                                 0
host_acceptance_rate                               0
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                                 0
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                      0
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                    4560
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        829
bathrooms_text                                     0
bedrooms                                         269
beds                                             834
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
calendar_updated                                4560
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                          865
first_review                                       0
last_review                                        0
review_scores_rating                            1066
review_scores_accuracy                          1067
review_scores_cleanliness                       1066
review_scores_checkin                           1068
review_scores_communication                     1066
review_scores_location                          1068
review_scores_value                             1068
license                                            0
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1066
dtype: int64

In [47]:
df_mean= act.fillna_mean(df_csv)
df_mean.head(3)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69
2,6695,https://www.airbnb.com/rooms/6695,20250619031426,2025-06-19,city scrape,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Comfortable, Fully Equipped private apartment...","Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/38ac4797-e7a4...,8229,...,4.94,4.53,4.72,STR-491702,f,11,11,0,0,0.72

In [48]:
df_mean.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                       45
neighborhood_overview                           2236
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                    923
host_about                                      1511
host_response_time                               531
host_response_rate                               531
host_acceptance_rate                             486
host_is_superhost                                176
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                    4560
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                     0
bedrooms                                           0
beds                                               0
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
calendar_updated                                4560
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                            0
first_review                                    1066
last_review                                     1066
review_scores_rating                               0
review_scores_accuracy                             0
review_scores_cleanliness                          0
review_scores_checkin                              0
review_scores_communication                        0
review_scores_location                             0
review_scores_value                                0
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                                  0
dtype: int64

In [49]:
df_median= act.fillna_median(df_csv)
df_median.head()

/opt/anaconda3/envs/Analitica/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/opt/anaconda3/envs/Analitica/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69
2,6695,https://www.airbnb.com/rooms/6695,20250619031426,2025-06-19,city scrape,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Comfortable, Fully Equipped private apartment...","Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/38ac4797-e7a4...,8229,...,4.94,4.53,4.72,STR-491702,f,11,11,0,0,0.72
3,8789,https://www.airbnb.com/rooms/8789,20250619031426,2025-06-19,city scrape,Curved Glass Studio/1bd facing Park,This unit is for sale. There will need to be o...,Beacon Hill is a historic neighborhood filled ...,https://a0.muscache.com/pictures/miso/Hosting-...,26988,...,4.97,4.97,4.59,NaN,f,8,8,0,0,0.22
4,10811,https://www.airbnb.com/rooms/10811,20250619031426,2025-06-19,city scrape,Bostons Best Rentals -Studio Prestigious Back Bay,Bostons Best Rentals offers a Stunning Back Ba...,A one-square mile neighborhood that is arguabl...,https://a0.muscache.com/pictures/45735/27548f7...,38997,...,4.00,5.00,4.67,NaN,f,12,12,0,0,0.08

In [50]:
df_median.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                       45
neighborhood_overview                           2236
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                    923
host_about                                      1511
host_response_time                               531
host_response_rate                               531
host_acceptance_rate                             486
host_is_superhost                                176
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                    4560
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                     0
bedrooms                                           0
beds                                               0
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
calendar_updated                                4560
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                            0
first_review                                    1066
last_review                                     1066
review_scores_rating                               0
review_scores_accuracy                             0
review_scores_cleanliness                          0
review_scores_checkin                              0
review_scores_communication                        0
review_scores_location                             0
review_scores_value                                0
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                                  0
dtype: int64

In [51]:
df_const = act.fillna_constant(df_csv)
df_const.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3781,https://www.airbnb.com/rooms/3781,20250619031426,2025-06-19,city scrape,HARBORSIDE-Walk to subway,Fully separate apartment in a two apartment bu...,"Mostly quiet ( no loud music, no crowed sidewa...",https://a0.muscache.com/pictures/24670/b2de044...,4804,...,4.96,4.85,4.88,NaN,f,1,1,0,0,0.21
1,5506,https://www.airbnb.com/rooms/5506,20250619031426,2025-06-19,city scrape,** Fort Hill Inn Private! Minutes to center!**,**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/miso/Hosting-...,8229,...,4.89,4.57,4.77,STR-490093,f,11,11,0,0,0.69
2,6695,https://www.airbnb.com/rooms/6695,20250619031426,2025-06-19,city scrape,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex","Comfortable, Fully Equipped private apartment...","Peaceful, Architecturally interesting, histori...",https://a0.muscache.com/pictures/38ac4797-e7a4...,8229,...,4.94,4.53,4.72,STR-491702,f,11,11,0,0,0.72
3,8789,https://www.airbnb.com/rooms/8789,20250619031426,2025-06-19,city scrape,Curved Glass Studio/1bd facing Park,This unit is for sale. There will need to be o...,Beacon Hill is a historic neighborhood filled ...,https://a0.muscache.com/pictures/miso/Hosting-...,26988,...,4.97,4.97,4.59,NaN,f,8,8,0,0,0.22
4,10811,https://www.airbnb.com/rooms/10811,20250619031426,2025-06-19,city scrape,Bostons Best Rentals -Studio Prestigious Back Bay,Bostons Best Rentals offers a Stunning Back Ba...,A one-square mile neighborhood that is arguabl...,https://a0.muscache.com/pictures/45735/27548f7...,38997,...,4.00,5.00,4.67,NaN,f,12,12,0,0,0.08

In [52]:
df_const.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
name                                               0
description                                       45
neighborhood_overview                           2236
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                    923
host_about                                      1511
host_response_time                               531
host_response_rate                               531
host_acceptance_rate                             486
host_is_superhost                                176
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               119
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2236
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                       0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                          0
bathrooms_text                                     0
bedrooms                                           0
beds                                               0
amenities                                          0
price                                            865
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
calendar_updated                                   0
has_availability                                 196
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
availability_eoy                                   0
number_of_reviews_ly                               0
estimated_occupancy_l365d                          0
estimated_revenue_l365d                            0
first_review                                    1066
last_review                                     1066
review_scores_rating                               0
review_scores_accuracy                             0
review_scores_cleanliness                          0
review_scores_checkin                              0
review_scores_communication                        0
review_scores_location                             0
review_scores_value                                0
license                                         1563
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                                  0
dtype: int64

In [53]:
# Ya que es un resumen, se visualizan directamente el resumen de los valores nulos
df_resu = act.resumen_nulos(df_csv)
df_resu

(                                              Nulos  Porcentaje (%)
 id                                                0            0.00
 listing_url                                       0            0.00
 scrape_id                                         0            0.00
 last_scraped                                      0            0.00
 source                                            0            0.00
 name                                              0            0.00
 description                                      45            0.99
 neighborhood_overview                          2236           49.04
 picture_url                                       0            0.00
 host_id                                           0            0.00
 host_url                                          0            0.00
 host_name                                         0            0.00
 host_since                                        0            0.00
 host_location                                   923           20.24
 host_about                                     1511           33.14
 host_response_time                              531           11.64
 host_response_rate                              531           11.64
 host_acceptance_rate                            486           10.66
 host_is_superhost                               176            3.86
 host_thumbnail_url                                0            0.00
 host_picture_url                                  0            0.00
 host_neighbourhood                              119            2.61
 host_listings_count                               0            0.00
 host_total_listings_count                         0            0.00
 host_verifications                                0            0.00
 host_has_profile_pic                              0            0.00
 host_identity_verified                            0            0.00
 neighbourhood                                  2236           49.04
 neighbourhood_cleansed                            0            0.00
 neighbourhood_group_cleansed                   4560          100.00
 latitude                                          0            0.00
 longitude                                         0            0.00
 property_type                                     0            0.00
 room_type                                         0            0.00
 accommodates                                      0            0.00
 bathrooms                                       829           18.18
 bathrooms_text                                    0            0.00
 bedrooms                                        269            5.90
 beds                                            834           18.29
 amenities                                         0            0.00
 price                                           865           18.97
 minimum_nights                                    0            0.00
 maximum_nights                                    0            0.00
 minimum_minimum_nights                            0            0.00
 maximum_minimum_nights                            0            0.00
 minimum_maximum_nights                            0            0.00
 maximum_maximum_nights                            0            0.00
 minimum_nights_avg_ntm                            0            0.00
 maximum_nights_avg_ntm                            0            0.00
 calendar_updated                               4560          100.00
 has_availability                                196            4.30
 availability_30                                   0            0.00
 availability_60                                   0            0.00
 availability_90                                   0            0.00
 availability_365                                  0            0.00
 calendar_last_scraped                             0            0.00
 number_of_reviews                                 0            0.00
 number_of_reviews_ltm                             0            0.00
 number_of_reviews_l30d                            0            0.00
 availability_eoy                                  0            0.00
 number_of_reviews_ly                              0            0.00
 estimated_occupancy_l365d                         0            0.00
 estimated_revenue_l365d                         865           18.97
 first_review                                   1066           23.38
 last_review                                    1066           23.38
 review_scores_rating                           1066           23.38
 review_scores_accuracy                         1067           23.40
 review_scores_cleanliness                      1066           23.38
 review_scores_checkin                          1068           23.42
 review_scores_communication                    1066           23.38
 review_scores_location                         1068           23.42
 review_scores_value                            1068           23.42
 license                                        1563           34.28
 instant_bookable                                  0            0.00
 calculated_host_listings_count                    0            0.00
 calculated_host_listings_count_entire_homes       0            0.00
 calculated_host_listings_count_private_rooms      0            0.00
 calculated_host_listings_count_shared_rooms       0            0.00
 reviews_per_month                              1066           23.38,
 'Total de valores nulos en el DataFrame: 34002')